### ISSUE TITLE
including this module results in "<ArrayPort> has no method isAddressable" errors

### ISSUE THREAD

**Issue by ryedin** [noflo/noflo-flow#10]
using noflo-nodejs@0.0.6, connected to noflu-ui (local copy of latest master as of 2 days ago)

As soon as I attempt to include this module in my application, the UI complains. I think some of the dependencies need to be updated to use the latest version of noflo, as I see noflo@0.4.5 is still referenced in places.

**Comment by bergie** [comment]
Now everything should be updated to NoFlo 0.8 API
